### ISSUE TITLE
Make calendar into a template

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/autoremind#1]
1. Install Node & Handlebars
2. Make each row of the table <tr> a handlebar loop something like this:

<img width="1185" alt="Screen Shot 2020-08-29 at 5 25 22 PM" src="https://user-images.githubusercontent.com/929079/91648441-a6676800-ea1c-11ea-9e44-446c1bdda242.png">

3. Get the data from Mukul and populate the table with dates and buttons

**Comment by osbornroxas02** [comment]
I implemented with this with the other code
