### ISSUE TITLE
Edit model needs to be template for each date

### ISSUE THREAD

**Issue by tedpedersen** [tedpedersen/autoremind#2]
1. Install Node and Handlebars.
2. Make a handlebars template out of the model so it can be reused for every date
3. Logic to map the model to the correct date (edit button on each date) Murkul will prob provide this, speak with him.
4. Populate the model with the data for each date
5. For adding or editing: Capture user input and pass to Murkul 

https://handlebarsjs.com/guide/#what-is-handlebars

**Comment by osbornroxas02** [comment]
Updates 08/30/31: initial set up work
1. created it in a feature/edit branch
2. created some moc backend work in order for me to be able to access the calendar info without mukuls backend work (pending) The moc backend might help speed up Jessicas work too since I've added handle bars and etc to it.
a. moved frontend to public folder
b. created utils folder, views folder and content for handlebars, gitignore and server.js code

**Comment by osbornroxas02** [comment]
Updates 08/31/20 : worked on 1, 2 & 3

1. created anew feature/modals branch and reinstalled the rest of the missing npm code
2. In calendar.handlebars I added new class <class="btn btn-primary btn-sm edit-button"> in order for me to bypass Jessica Lam portion so I can work on the modal. Im probably going to need to change my code once Jessica finishes her portion
3. I created a public/js/main.js and added some jquery to get the dates into the modal
4. I had to change a few thing in the server.js in order for my code to work again. We might have accidentally erased lines of code
5. I also added a .env folder and added some data into it

* waiting for mukuls portion of the /api to finish 4 & 5 on my issues list

**Comment by osbornroxas02** [comment]
Just added a pull request in a fearture/calendar branch

1. Updated naming ID for Model.handlebars
2. Finished api calls in appointment-routes.js
3. 80% done with code in main.js.
      a. Finished [Add Reminder] & [edit] button function
      b. Finished [client name] [time] functions
* the user inputs [name, time, date, id] are captured and console.log() ready for Mukul to reformat and use in his code

*Pending for tomorrow night
      c.[save] & [delete] buttons functions (edited)

**Comment by osbornroxas02** [comment]
Final code

Change primary key to id! this caused errors in the code
Update api routes 
added update api
