### ISSUE TITLE
Final Checks & link fix

### ISSUE THREAD

**Issue by osbornroxas02** [tedpedersen/autoremind#8]
1. Double check Github link. CSS seems odd.
2. Recheck Heroku link.
3. Test code. 

*** < npm start > from terminal seems to work but I haven't tried from the log in page

**Comment by tedpedersen** [comment]
I get this error when I try to run the app, not sure how to fix it, or what it is:

(node:8237) UnhandledPromiseRejectionWarning: SequelizeConnectionError: Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.
    at ConnectionManager.connect (/Users/tedpedersen/Sites/autoremind-master/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tedpedersen** [comment]
That error will need to be fixed for the app to work on heroku. I have no idea what it is or how to fix it.

**Comment by osbornroxas02** [comment]
Ted and Os worked on this with TA's Issues came from Heroku naming
